active_modules: [pygments, blog, tags, thumbimg, gallery]
author: Aurélien Gâteau
canonical_url: https://agateau.com/
ignore_files:
    - "!.well-known"
    - .*
    - _*
    - node_modules
    - "*.yml"
    - Makefile
    - README.md
    - storage
    - "config*.mk"
modules:
    pygments:
        style: tango
    blog:
        feed_url: /feed
        archive_year_url: /<year>/
    tags:
        tag_feed_url: /tags/<tag>/feed
feed:
    name: "Aurélien Gâteau"
    subtitle: "Code, pixels, user interfaces and occasional developer tips"
css_hash: ba324c355e0fa996b60d3cebf3dc5ceb
